services:
  pygeoapi:
    image: geopython/pygeoapi
    container_name: pygeoapi
    ports:
      - "5050:80"
    volumes:
      - ./local.config.yml:/pygeoapi/local.config.yml
    environment:
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_OPENAPI=/pygeoapi/local.openapi.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
